### ISSUE TITLE
Module not found: Error: Can't resolve 'img/network/cross.png' 

### ISSUE THREAD

**Issue by ASVBPREAUBV** [Lighthouse-io/react-visjs-timeline#11]
Hello Guys,

im not sure if im right here or if this is just a webpack config issue.
i cant load the module.

this is my error:
ERROR in css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/vis/dist/vis.css

**Comment by willmcclellan** [comment]
@ASVBPREAUBV this comment might help? https://github.com/Lighthouse-io/react-visjs-timeline/issues/2#issuecomment-249730054

**Comment by willmcclellan** [comment]
@ASVBPREAUBV also make sure you have install `vis` as a dependency
