### ISSUE TITLE
onUpdate

### ISSUE THREAD

**Issue by prabuvenkat** [Lighthouse-io/react-visjs-timeline#16]
How do I specify an onUpdate handler ? It did not help adding onUpdate as a function (taking item, callback as arguments) in options passed to Timeline.

**Comment by ErinsMatthew** [comment]
@prabuvenkat Is this like what you are doing already?  If so, what is the issue you are facing?  In order for `onUpdate` to fire, you must make sure that `editable` is set to `true` per [the referenced documentation](http://visjs.org/docs/timeline/#Editing_Items).

```
import React, {Component} from 'react';
import Timeline from 'react-visjs-timeline';

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      options: {
        editable: true,
        onUpdate: (item, callback) => {
          // implement your onUpdate actions here, or you could reference another function
          // see <http://visjs.org/docs/timeline/#Editing_Items>
        }
      },
      items: [
        { start: '2017-01-01', end: '2017-01-31', content: 'January' },
        { start: '2017-02-01', end: '2017-02-28', content: 'February' }
      ]
    };
  }

  render() {
    return (
      <Timeline {...this.state}/>
    );
  }
}
```

**Comment by prabuvenkat** [comment]
Hei!
Yes, this is exactly what I have.. but the function is never invoked. My items are of type 'range'. I am trying to get the function when I change the end/start of a block from the ui itself..

Am I wrong in assuming this is the function which will be invoked when I, say ,modify the range of one of the items ?

<pre>
    selectable: true,
    editable: true,
    onUpdate: (item, callback) => {
      console.log('{update} item', item);
      console.log('{update} cb: ', callback);
      callback(item);
    },
</pre>

**Comment by prabuvenkat** [comment]
I realize onMove is what I must be using (not onUpdate) and it works perfectly!
