### ISSUE TITLE
when re-render in ie, all items move to top for moment(about 1s)

### ISSUE THREAD

**Issue by chocholand** [Lighthouse-io/react-visjs-timeline#19]
"react-visjs-timeline": "^1.3.3",
"vis": "^4.20.0"

`
<Timeline
          options={options}
          items={mergeSortedArr}
          groups={groups}
          selectHandler={this.selectHandler}
          selection={this.selectedFolderIds}
        />
`

when this.selectedFolderIds is changed, all item move to top in IE 11.
before
![2017-05-31 9 10 40](https://cloud.githubusercontent.com/assets/6572227/26631365/a4f0f2b2-4645-11e7-9bad-9f7fad95b9c3.png)

after
![2017-05-31 9 10 30](https://cloud.githubusercontent.com/assets/6572227/26631369/a8608a8e-4645-11e7-9267-7b702397b836.png)

**Comment by jonathanchrisp** [comment]
Hi @chocholand, thanks for raising the issue. Do you get the same behaviour when using `v4.19.1` of vis.js? The vis.js team released the latest version 10 days ago and it appears that there are a few issues.

**Comment by chocholand** [comment]
@jonathanchrisp When I first tried v4.19.1, I got an error and upgraded to v.4.20.0. But the error exsit.

**Comment by jonathanchrisp** [comment]
Hey @chocholand, what was the error reported?

**Comment by chocholand** [comment]
@jonathanchrisp when selection value is changed, all item move to top for 1s.

**Comment by jonathanchrisp** [comment]
Hey @chocholand, unfortunately, I can't do much without an error or a code snippet to be able to reproduce the error. If you're able to provide this would be greatly appreciated.

**Comment by chocholand** [comment]
@jonathanchrisp I'm making reproduced the error your react boilerplate.
But, select item is not working.

```
class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      selectedIds: [1,2,3]
    }
  }
  render() {
    return (
      <div className="App">
        <p className="header">A basic timeline. You can move and zoom the timeline, and select items.</p>
        <Timeline
          {...basicExample}
        />
        <p className="header">This example demonstrate using groups. Note that a DataSet is used for both
          items and groups, allowing to dynamically add, update or remove both items
          and groups via the DataSet.</p>
        <Timeline
          {...groupsExample}
          selectHandler={this.selectHandler.bind(this)}
          selection={this.state.selectedIds}
        />
      </div>
    )
  }

  selectHandler(props) {
    const { items } = props
    this.setState({
      selectedIds: [5, 9, 18]
    })
  }
}
```

selection is not working.

**Comment by jonathanchrisp** [comment]
Hey @chocholand, I've figured this out, I'll raise a PR to fix, really helped with the detailed code above. Thank you. I'll link this issue on the PR 🎉

**Comment by jonathanchrisp** [comment]
Hey @chocholand, I've raised a PR to fix this issue here: https://github.com/Lighthouse-io/react-visjs-timeline/pull/20. Hopefully, @willmcclellan might have time to quickly review this tomorrow 😄
