### ISSUE TITLE
Toggle nested groups

### ISSUE THREAD

**Issue by allenylzhou** [Lighthouse-io/react-visjs-timeline#22]
I don't think toggling nested groups works. I forked the repository to see if I can figure it out but I'm running into trouble running this locally.

Changing import Timeline from 'react-vjsjs-timeline' in examples/src/App.js to import Timeline from '../../build' causes a bunch of dependency issues. Are there any instructions on how to test my changes?

Failed to compile.

Error in ../build/index.js
Module not found: 'style' in ~/react-visjs-timeline/build

 @ ../build/index.js 13:0-27

**Comment by willmcclellan** [comment]
@allenylzhou because we have a build step on install it's tricky to test locally or using github as the source. A workaround is to use `npm link` and build locally, or publish your fork to a private registry
