### ISSUE TITLE
Are there any plans to support visjs timeline methods?

### ISSUE THREAD

**Issue by allenylzhou** [Lighthouse-io/react-visjs-timeline#25]
http://visjs.org/docs/timeline/#Methods

The component currently does not pass a ref for me to call these methods on.

**Comment by Ezekiah** [comment]
Is it possible to call setWindow , on the timeline ?

**Comment by willmcclellan** [comment]
@allenylzhou We do support the main methods `setOptions`, `setItems`, `setSelection` etc, but it's in a react declarative style - via prop config. The whole purpose of this module is to abstract away visjs timeline into a more declarative pattern. We don't support all methods currently, but happy to take suggestions and PRs to support more. 

@Ezekiah If you pass `start`/`end` props along with `animate`, the component will use `setWindow` to apply those values

**Comment by RamK777-stack** [comment]
Is this possible to use Zoom in and zoom out methods ? @willmcclellan
