### ISSUE TITLE
PropTypes warning

### ISSUE THREAD

**Issue by ms007** [Lighthouse-io/react-visjs-timeline#28]
using Timeline displays a warning about deprecated PropTypes usage: 

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by willmcclellan** [comment]
Fixed with #29
