### ISSUE TITLE
get it to run

### ISSUE THREAD

**Issue by t-hughes** [Lighthouse-io/react-visjs-timeline#30]
How do you get this up and running? I've downloaded the files and ran the npm install of react-visjs-timeline but doing an npm start wont work and opening it with live-server shows nothing.

**Comment by willmcclellan** [comment]
@t-hughes So you should be able to cd into the `examples` directory, yarn/npm install from there and `npm start`. Just to check you've done that from the examples dir and not the root?

**Comment by t-hughes** [comment]
That worked, thanks.
