### ISSUE TITLE
Fix Warning when using react 16

### ISSUE THREAD

**Issue by mouhsinelonly** [Lighthouse-io/react-visjs-timeline#32]
Warning: Timeline.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.

**Comment by llonchj** [comment]
@mouhsinelonly see #35

**Comment by lidakis** [comment]
The solution is here:
**1) find the following in file: node/modules/react-visjs-timeline/build.index.js @ line:75**

`_createClass(Timeline, [{
    key: 'componentWillMount',
    value: function componentWillMount() {
      this.state = {
        // NOTE we store custom times on the state to enable us to diff with new
        // custom times and add or remove the elements with visjs
        customTimes: []
      };
     }
  },`
 
**2) Replace it with:**

`_createClass(Timeline, [{
    key: 'componentWillMount',
    value: function componentWillMount() {

      // this is the new workaround for replacement of 'this.state' to this.setState  
       this.setState({
           customTimes: []
       });
    }
  },`

**Comment by willmcclellan** [comment]
Fixed in #35
