### ISSUE TITLE
React to 16 doesn't show timeline

### ISSUE THREAD

**Issue by KamilKmitaLasoft** [Lighthouse-io/react-visjs-timeline#38]
After update react to version 16 my timeline get style visibility: hidden; , when manualy change it to visible timeline is not work fine - i cant drag , zoom in etc.

`    touch-action: pan-y;
    user-select: none;
    -webkit-user-drag: none;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
    visibility: hidden;
    height: 205px;
`
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-visjs-timeline": "^1.3.4-beta",
    "vis": "^4.20.1",

**Comment by itsnydell** [comment]
I went back to `vis` at `4.19.1` and the problem went away.

**Comment by wessel369** [comment]
I had to explicitly set the visibility to visible in the css for  .vis-timeline ...... for some reason when it renders there is an inline style setting it as invisible..

**Comment by yampelo** [comment]
```
.vis-timeline {
    visibility: visible !important;
}
```

The above CSS fixes the issue for me.
