### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by jason-weirather** [Lighthouse-io/react-visjs-timeline#39]
# Overview
Importing produces the following error

`Module not found: Can't resolve 'vis/dist/vis-timeline-graph2d.min' in '#############/node_modules/react-visjs-timeline/build'`

## Package versions
react-visjs-timeline: 1.4.0
vis version: 4.21.0

## Steps to reproduce
```js
import {Timelines as TL} from 'react-visjs-timeline';
```

**Comment by inev** [comment]
I'm getting the same error :/

**Comment by jason-weirather** [comment]
@inev I am a React novice, but I never did find a way to get this to work but i had some success wrapping visjs in my own container.

```js
import React from 'react';
import styles from '../../../node_modules/vis/dist/vis.min.css'
const vis = require('vis');
const uuidv4 = require('uuid/v4');

class VisTimeline extends React.Component {
	constructor(props) {
		super(props);
        this.state = {id:uuidv4()};
        //console.log('construct timeline')
    }
    render () {
        //console.log('in element VisTimeline render');
        console.log('rendering timeline');
    	return (<div>
    	    {this.props.entries ? <div id={this.state.id}></div> : <div>No timeline data selected</div>}
            </div>
    		);
    }
    componentDidMount () {
        if (! this.props.entries) return;
    	var container = document.getElementById(this.state.id);
        //console.log([container,this.props.entries,this.props.groups,this.props.options]);
    	var timeline = new vis.Timeline(container,this.props.entries,this.props.groups,this.props.options);
        var that = this;
        if (this.props.select) {
            timeline.on('select',function(properties){
                that.props.select(properties);
            });
        }
    }	
}
```

I'm probably doing all kinds of noob things wrong, and I have some issues with triggering the renders of this component at the right time from above after events and have to do some jenky controls to get it to render at the appropriate times, but its working for me.  I hope this may help you find something that works.  The timelines look so good!

**Comment by inev** [comment]
@jason-weirather I actually got it to work but it had other problems mentioned in other issues. When you switched pages, it didn't reload correctly for example. Since the library seems to be updated only occasionally I figured it's safer to work with `visjs` directly like you did.

A couple pointers on your code:
* You are going to want to use the `ref` attribute of react like the code below, it's a lot cleaner.
* Using the provided `DataSet` component will provide you with the two way binding so it auto updates.
```
componentDidMount() {
  this.timelineDataSet = new DataSet([]);
  this.timeline = new Timeline(this.refs.timeline, this.timelineDataSet, {
    //options
  });
  this.timeline.setWindow(this.oneMonthBefore, this.now);
}

render() {
  return <div ref="timeline"></div>;
}
```

**Comment by ecirish** [comment]
@inev would you happen to have a working example of this somewhere we could take a look at?

**Comment by inev** [comment]
@ecirish Sorry, unfortunately, the code is in a private repo so I can't share a link but if you have a specific question I can answer it.

**Comment by cacharrin** [comment]
Just resolved it... I just did `npm install vis`
Shouldn't `react-visjs-timeline` install this dependecy?

**Comment by austingayler** [comment]
Thanks, above fix worked for me.

**Comment by attila135786** [comment]
I ended up installing vis-timeline instead of vis and it resolved the issue.
