### ISSUE TITLE
Set Fixed Dates

### ISSUE THREAD

**Issue by sabina4** [Lighthouse-io/react-visjs-timeline#42]
Hello,

How can I set the timeline to show yesterday, today and tomorrow only? 

Thanks

**Comment by rickysahu** [comment]
vis offers a way to use buttons http://visjs.org/examples/timeline/interaction/animateWindow.html but im not sure how to get them to interact with the react based timeline. any suggestions?

**Comment by rickysahu** [comment]
looks like its answered here https://github.com/Lighthouse-io/react-visjs-timeline/issues/33#issuecomment-330092443
