### ISSUE TITLE
Feature Request: Groups

### ISSUE THREAD

**Issue by HorseBinky** [Lighthouse-io/react-visjs-timeline#5]
Hi!
Very nice work! Is it possible to use timeline groups with this wrapper?
Thanks!!

**Comment by roboslone** [comment]
+1

**Comment by willmcclellan** [comment]
You can follow #4 for this feature

**Comment by roboslone** [comment]
#4 is merged, is there any progress here?

**Comment by roboslone** [comment]
Also, there're now nested groups as well (https://github.com/almende/vis/issues/2300), I haven't been able to try them yet, but I think they should be taken into account here.

**Comment by roboslone** [comment]
@mx781 , it looks like group support is already in master, do you think this issue can be closed after docs update?
