### ISSUE TITLE
Feature Request: Specify item content with JSX

### ISSUE THREAD

**Issue by lordi** [Lighthouse-io/react-visjs-timeline#6]
It would be nice to be able to specify item content with a JSX object instead of a String:

```
const items = [{start: ...., content: <div>Hello!</div>}];
```

**Comment by ErinsMatthew** [comment]
Have you tried using the `template` [option](http://visjs.org/docs/timeline/#Configuration_Options) to specify your JSX as an item template? See "React templates" [here](http://visjs.org/docs/timeline/).  Something like:

`const options = { template: ( item, element, data ) => { ReactDOM.render(<b>{item.content}</b>, element) } };`

**Comment by jonathanchrisp** [comment]
Hi @lordi, did you try @ErinsMatthew suggestion in the end? Apologies for the delay getting back to you. Let me know if this resolved your issue.

**Comment by vmazet** [comment]
Hi everyone! @ErinsMatthew  suggestion work for me ! thanks a lot !

**Comment by Wgil** [comment]
I'm trying to use `groupTemplate` options but for some reason the id of my groups is printed along with the template.
```
static options = {
    width: '100%',
    align: 'center',
    orientation: 'top',
    stack: false,
    groupTemplate: function(item, element, data) {
      return ReactDOM.render(<b>{item.content}</b>, element)
    }
  }
```
This is how it looks:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/12855914/61741948-02fb4c80-ad60-11e9-8b8e-86ebcdfeea37.png">
